version: '3.8'

services:
  app:
    build: .
    container_name: luam-app
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=luamcandle
      - DB_USER=root
      - DB_PASS=
    depends_on:
      - db
    networks:
      - luam-network

  db:
    image: mysql:5.7
    container_name: luam-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: luamcandle
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - luam-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: luam-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_ARBITRARY: 1
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - luam-network

networks:
  luam-network:
    driver: bridge

volumes:
  db_data:
